name: brain-gnn
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pyg  # PyTorch Geometric
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - scanpy
  - python-igraph
  - leidenalg
  - h5py
  - pytorch-lightning
  - pip
  - pip:
    - synapseclient
    - hydra-core
    - wandb
    - torchmetrics
    - fastapi
    - uvicorn
